env:
  es6: true
  browser: true
  jest/globals: true
plugins:
  - '@typescript-eslint'
  - 'jest'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    legacyDecorators: true
rules:
  'indent': 
    - error
    - 2
    - SwitchCase: 1
  'linebreak-style':
    - error
    - unix
  'quotes':
    - error
    - single
  'semi':
    - error
    - always
  'no-console': off
  'no-empty': error
  'keyword-spacing': error
  'no-mixed-spaces-and-tabs': error
  'no-trailing-spaces': error
  'max-len': warn
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-function': warn
